### ISSUE TITLE
Glitch

### ISSUE THREAD

**Issue by Itsmeyaywow** [bcrhbrhcdb/Noobs-Unblocked-Games-POST-BETA#32]
The pop-up screen shows up and won't go away. The one that says the time.

**Comment by bcrhbrhcdb** [comment]
Are cookies enabled?

**Comment by bcrhbrhcdb** [comment]
Sometimes when you switch pages it will show, but once you close it on all of the pages it will be gone until the next announcement. Fixing it rn.
